[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
description = "An adaptor that chunks up elements and flushes them after a timeout or when the buffer is full."
license = "MIT OR Apache-2.0"
name = "tokio-batch"
version = "0.1.0"

[dependencies]
futures = "0.1.16"
tokio-core = "0.1.10"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"